main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Home, name='home'),
    path('event-details/<str:slug>/', views.EventDetails, name='event-details'),
    path('all-events/', views.EventView, name='event'),
    path('about-us/', views.AboutView, name='about'),
    path('contact-us/', views.ContactView, name='contact'),
    path('event-photos-videos/', views.MediaLibraryView, name='media'),
    path('photo-details/<int:id>/', views.PhotoDetailView, name='photo-detail'),
    path('membership-donation/', views.DonationView, name='donate'),
]

sanatan_society/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
if settings.DEBUG:
    urlpatterns= urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns= urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

main/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField

# Create your models here.
class EventList(models.Model):
    event_name = models.CharField(max_length=264)
    #introduction = models.TextField(blank=True, null=True)
    #schedule = models.TextField(blank=True, null= True)
    #donation = models.TextField(blank=True, null=True)
    #culture_program = models.TextField(blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    images = models.ImageField(upload_to='event_images')
    event_date = models.CharField(max_length=50, blank=True)
    year = models.CharField(max_length=50, blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.event_name)
        super(EventList, self).save(*args, **kwargs)
    
    def __str__(self) -> str:
        return self.event_name
    class Meta:
        ordering = ['-created']

class Banner(models.Model):
    image = models.ImageField(upload_to='banner')

class AboutUs(models.Model):
    title = models.CharField(max_length=264, blank=True, null=True)
    text = models.TextField()
    images = models.ImageField(upload_to='about-us-home', blank=True, null=True)


class AboutPage(models.Model):
    title = models.CharField(max_length=264, blank=True, null=True)
    text = models.TextField()
    images = models.ImageField(upload_to='about-us', blank=True, null=True)

class TeamMembers(models.Model):
    name = models.CharField(max_length=64)
    title = models.CharField(max_length=264)
    phone = models.CharField(max_length=30)
    email = models.EmailField(max_length=64)
    profile_pic = models.ImageField(upload_to='team_members', blank=True, null=True)

    def __str__(self) -> str:
        return self.name

class TestimonialSection(models.Model):
    name = models.CharField(max_length=64)
    text = models.CharField(max_length=600)
    image = models.ImageField(upload_to='testimonial', blank=True, null=True)

    def __str__(self) -> str:
        return self.name

class ContactUs(models.Model):
    name = models.CharField(max_length=64)
    email = models.EmailField(max_length=264)
    subject = models.CharField(max_length=264)
    message = models.TextField()

    def __str__(self) -> str:
        return self.name

class DonateModel(models.Model):
    name = models.CharField(max_length=50)
    price_range = models.CharField(max_length=1000)
    image = models.ImageField(upload_to='donation')

    def __str__(self) -> str:
        return self.name  

# class Category(models.Model):
#     name = models.CharField(max_length=64)
#     slug = models.SlugField(unique=True, blank=True)

#     def save(self,*args, **kwargs):
#         if not self.slug:
#             self.slug = slugify(self.name)
#         super(Category, self).save(*args, **kwargs)
            

class MediaLibrary(models.Model):
    event_name = models.ForeignKey(EventList, on_delete=models.CASCADE)
    videos = models.FileField(upload_to='media_video', blank=True, null=True)
    photos = models.ImageField(upload_to='media_photo', blank=True, null=True)
    media_year = models.CharField(max_length=50, help_text='2021')

    def __str__(self) -> str:
        return self.event_name.event_name

main/forms.py
from django import forms
from .models import ContactUs

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ('__all__')

main/views.py
from django.shortcuts import render, redirect
from .models import EventList, AboutPage, TeamMembers,AboutUs, TestimonialSection, DonateModel, MediaLibrary, Banner
from .forms import ContactForm
from django.contrib import messages
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.conf import settings
import threading
# Create your views here.

def send_email_thread(subject, message, from_email, to_email):
    send_mail(subject, message, from_email, to_email, fail_silently=True)

def Home(request):
    banners = Banner.objects.all()
    events = EventList.objects.all()[:4]
    about = AboutUs.objects.first()
    review = TestimonialSection.objects.all()
    context = {'banners':banners, 'events': events, 'about':about, 'review':review}
    return render(request, 'main/home.html', context)

def EventDetails(request,slug):
    events = EventList.objects.get(slug=slug)
    context = {'events':events}
    return render(request, 'main/event_details.html',context)

def EventView(request):
    events = EventList.objects.all()
    context = {'events':events}
    return render(request, 'main/event_list.html', context)

def AboutView(request):
    texts = AboutPage.objects.first()
    print(texts)
    teams = TeamMembers.objects.all()
    context = {'text':texts, 'teams':teams}
    return render(request, 'main/about.html', context)

def ContactView(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            client_message = form.cleaned_data.get('message')
            form.save()
            messages.success(request, "Message sent successfully")

            subject = 'You received a new message from SSOB'
            message = f'Hi {client_message}'
            from_email = settings.DEFAULT_FROM_EMAIL
            to_email = [form.cleaned_data.get('email')]

            # Start a new thread to send the email
            thread = threading.Thread(
             target=send_email_thread,
             args=(subject, message, from_email, to_email),
            )
            # jay.ns.cloudflare.com
            # ruth.ns.cloudflare.com
            thread.start()
            return redirect('main:contact')

    context = {'form': form}
    return render(request, 'main/contact.html', context)


def MediaLibraryView(request):
    event_img = MediaLibrary.objects.filter(media_year='2023')
    event_name_list = MediaLibrary.objects.all()
    context = {'event_img':event_img, 'event_name_list':event_name_list}
    return render(request, 'main/media_library.html', context)

def PhotoDetailView(request, id):
    name = MediaLibrary.objects.get(id=id)
    photos = MediaLibrary.objects.filter(event_name=name.event_name)
    context = {'name':name, 'photos':photos}
    return render(request, 'main/photo_detail.html', context)

def DonationView(request):
    donate_list = DonateModel.objects.all()
    context = {'donates':donate_list}
    return render(request, 'main/donate.html', context)

templates/banner.html
<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
      {% for banner in banners %}
          <div class="carousel-item {% if forloop.first %}active{% endif %}">
              <img src="{{ banner.image.url }}" class="d-block w-100 img-fluid banner-img" alt="...">
          </div>
      {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
  </button>
</div>

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="{% static 'images/icon.jpg' %}">
    <link rel="stylesheet" href="{% static 'style/main.css' %}">

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    

    <title>SSOB| {% block title %} {% endblock title %} </title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div>
        {% block content %}
        
        {% endblock content %}
    {% include 'footer.html' %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

templates/footer.html
<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="mt-5">
    <!-- Footer -->
    <footer
            class="text-center text-lg-start text-white"
            style="background-color: #45526e"
            >
      <!-- Grid container -->
      <div class="container p-4 pb-0">
        <!-- Section: Links -->
        <section class="">
          <!--Grid row-->
          <div class="row">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">
                SANATAN SOCIETY OF BOSTON
              </h6>
              <p>
                Here you can use rows and columns to organize your footer
                content. Lorem ipsum dolor sit amet, consectetur adipisicing
                elit.
              </p>
            </div>
            <!-- Grid column -->
  
            <hr class="w-100 clearfix d-md-none" />
  
            <!-- Grid column -->
            {% comment %} <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
              <p>
                <a class="text-white" href=''>MDBootstrap</a>
              </p>
              <p>
                <a class="text-white" href=''>MDWordPress</a>
              </p>
              <p>
                <a class="text-white" href=''>BrandFlow</a>
              </p>
              <p>
                <a class="text-white" href=''>Bootstrap Angular</a>
              </p>
            </div> {% endcomment %}
            <!-- Grid column -->
  
            <hr class="w-100 clearfix d-md-none" />
  
            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">
                Useful links
              </h6>
              <p>
                <a class="text-white" href='{% url "main:home" %}'>Home</a>
              </p>
              <p>
                <a class="text-white" href='{% url "main:about" %}'>About Us</a>
              </p>
              <p>
                <a class="text-white" href='{% url "main:event" %}'>Events</a>
              </p>
              <p>
                <a class="text-white" href='{% url "main:media" %}'>Media</a>
              </p>
            </div>
  
            <!-- Grid column -->
            <hr class="w-100 clearfix d-md-none" />
  
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
              <p><i class="bi bi-geo-alt-fill mr-3"></i> New York, NY 10012, US</p>
              <p><i class="bi bi-envelope-fill mr-3"></i> info@gmail.com</p>
              <p><i class="bi bi-telephone-fill mr-3"></i> + 01 234 567 88</p>
              <p><i class="bi bi-telephone-fill mr-3"></i> + 01 234 567 89</p>
            </div>
            <!-- Grid column -->
          </div>
          <!--Grid row-->
        </section>
        <!-- Section: Links -->
  
        <hr class="my-3">
  
        <!-- Section: Copyright -->
        <section class="p-3 pt-0">
          <div class="row d-flex align-items-center">
            <!-- Grid column -->
            <div class="col-md-7 col-lg-8 text-center text-md-start">
              <!-- Copyright -->
              <div class="p-3">
                © 2024 Copyright: Developed By
                <a class="text-white" href="https://www.linkedin.com/in/clinton-biswas-ponti/"
                   >Clinton Biswas </a>
              </div>
              <!-- Copyright -->
            </div>
            <!-- Grid column -->
  
            <!-- Grid column -->
            <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
              <!-- Facebook -->
              <a
                 class="btn btn-outline-light btn-floating m-1"
                 class="text-white"
                 role="button"
                 href='https://www.facebook.com/pujaudjaponparishad.boston?mibextid=kFxxJD'
                 ><i class="bi bi-facebook"></i
                ></a>
  
              <!-- Twitter -->
              <a
                 class="btn btn-outline-light btn-floating m-1"
                 class="text-white"
                 role="button"
                 ><i class="bi bi-twitter"></i
                ></a>
  
              <!-- Google -->
              <a
                 class="btn btn-outline-light btn-floating m-1"
                 class="text-white"
                 role="button"
                 ><i class="bi bi-google"></i
                ></a>
  
              <!-- Instagram -->
              <a
                 class="btn btn-outline-light btn-floating m-1"
                 class="text-white"
                 role="button"
                 ><i class="bi bi-instagram"></i
                ></a>
            </div>
            <!-- Grid column -->
          </div>
        </section>
        <!-- Section: Copyright -->
      </div>
      <!-- Grid container -->
    </footer>
    <!-- Footer -->
  </div>
  <!-- End of .container -->

templates/main/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    About Us
{% endblock title %}

{% block content %}
<div class="d-flex justify-content-center align-items-center" style="height: 130px; background-color: #F4C431;">
    <h2 style="margin: 0; font-weight: bolder; letter-spacing: 2px;">About Us</h2>
</div>
    <div class="container mt-3 mb-5">
        <div class="row">
            <div class="col-sm-7">
                <div class="mb-3">
                    <h1>{{text.title}}</h1>
                    <p>{{text.text|linebreaks}}</p>
                </div>
            </div>
            <div class="col-sm-5">
                <img src={{text.images.url}} alt="" sizes="" srcset="" style="width: 100%; max-width: 100%; border-radius: 10px;">
            </div>
        </div>

        <div class="row justify-content-md-center mt-5">
            <div class="col-12 col-md-10 col-lg-8 col-xl-7 col-xxl-6">
              <h2 class="mb-4 display-5 text-center">Our Team</h2>
              <p class="text-secondary mb-5 text-center lead fs-4">We are a group of innovative, experienced, and proficient teams. You will love to collaborate with us.</p>
              <hr class="w-50 mx-auto mb-5 mb-xl-9 border-dark-subtle">
            </div>
          </div>
          <div class="mt-3">
            <div class="row gy-4 gy-lg-0 gx-xxl-5">
                
                {% for team in teams %}
                <div class="col-12 col-md-6 col-lg-3">
                    <div class="card border-primary shadow-sm mb-3">
                        <div class="card-body p-0">
                            <figure class="m-0 p-0">
                                <img class="img-fluid border rounded" loading="lazy" src={{team.profile_pic.url}} style="height: 215px; width: 100%; max-width: 100%;">
                                <figcaption class="m-0 p-4">
                                    <h4 class="mb-1">{{team.name}}</h4>
                                    <p class="text-secondary mb-0">{{team.title}}</p>
                                    <p class="text-secondary mb-0">{{team.email}}</p>
                                    <p class="text-secondary mb-0">{{team.phone}}</p>
                                </figcaption>
                            </figure>
                        </div>
                    </div>
                </div>  
                {% endfor %}
                    
            </div>
            
          </div>

    </div>

{% endblock content %}
    

templates/main/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    Contact
{% endblock title %}


{% block content %}
<div class="d-flex flex-column justify-content-center align-items-center" style="height: 130px; background-color: #F4C431;">
    <h2 style="margin: 0; font-weight: bolder; letter-spacing: 2px;">Contact Us</h2>
    <p style="margin-top: 10px;">Feel free to contact us.</p>
</div>
    <div class="container" style="background-color: #f8f9fa;">
        <div class="row">
            <div class="col-sm-5 d-flex justify-content-center align-items-center">
                <img src="{% static 'images/contact1.png' %}" alt="" class="animated-image img-fluid">
            </div>
            
            <div class="col-sm-7">
                
                <form method="POST" class="p-5">
                    {% if messages %}
                    
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {% endfor %}
                    
                    {% endif %}
                    {{form|crispy}}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning" style="width: 100%; max-width: 100%;">Send Message</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
    

templates/main/donate.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Donation
{% endblock title %}


{% block content %}
<div class="d-flex flex-column justify-content-center align-items-center" style="height: 130px; background-color: #F4C431;">
    <h2 style="margin: 0; font-weight: bolder; letter-spacing: 2px;">Membership Donation</h2>
</div>
<div class="container my-5">
    <div class="d-flex flex-column justify-content-center align-items-center">
        <h2 style="margin: 0; font-weight: bolder; letter-spacing: 2px;">Donate Now</h2>
        <p style="margin-top: 15px; font-size: 1.2rem; font-weight: 700; text-align: center;">Payment through the website requires 2.7% additional processing fee. To avoid the processing fee, send membership or concert donations using Zelle at bcaaaz.finance@gmail.com</p>
    </div>
    <div class="mt-3">
        <div class="row">
            
            {% for donate in donates %}
                <div class="col-sm-3">
                    <div class="card-container position-relative mb-3">
                        <img src={{donate.image.url}} class="img-fluid" alt="Card Image" height="300px" width="100%" max-width="100%">
                        <div class="overlay">
                          <div style="font-size: 1rem;">{{donate.name}}&nbsp;$({{donate.price_range}})</div><br>
                          <a href="#" class="btn btn-primary card-button">Donate</a>
                        </div>
                      </div>
                </div>
            {% endfor %}
                
        </div>
        
    </div>
</div>
    
{% endblock content %}
    

templates/main/event_details.html
{% extends 'base.html' %}
{% block title %}
    Event Details
{% endblock title %}


{% block content %}
        <div class="d-flex justify-content-center align-items-center" style="height: 130px; background-color: #F4C431;">
            <h2 style="margin: 0; font-weight: bolder; letter-spacing: 2px;">{{events.event_name}}({{events.year}})</h2>
        </div>
        <div class="container my-3">
            <div class="card mb-3" style="border: none;">
                <div class="row g-0">
                  <div class="col-md-4">
                    <img src={{events.images.url}} class="img-fluid rounded-start" alt="...">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h5 class="card-title">{{events.event_name}}</h5>
                      <p class="card-text">Start Date: <small class="text-muted">{{events.event_date}}</small></p>
                    </div>
                  </div>
                </div>
              </div>
              <hr>
              <div class="mt-2">
                <p class='mb-3'>{{ events.body|safe|linebreaks }}</p>
              </div>
        </div>
{% endblock content %}
    

templates/main/event_list.html
{% extends 'base.html' %}

{% block title %}
    all-event
{% endblock title %}

{% block content %}
<div class="container mt-3 mb-5">
    <div class="mb-4" style="text-align: center;">
        <h1 style="
            display: inline-block;
            padding: 5px;
            background: linear-gradient(to right, #ff7e5f, #feb47b);
            -webkit-background-clip: text;
            color: transparent;
            border-bottom: 3px solid #ff7e5f;
        ">Our Events</h1>
    </div>
    <div class="row">
                
        {% for event in events %}
            <div class="col-lg-6">
                <div class="card shadow mb-3">
                    <img src={{event.images.url}} class="card-img-top" alt="..." height="350">
                    <div class="card-body">
                      <h5 class="card-title">{{event.event_name}}</h5>
                      <p class="card-text">{{event.body|striptags|truncatechars:100 }}</p>
                      <hr>
                      <a href="{% url 'main:event-details' event.slug %}" type="button" class="btn btn-outline-info align-items-center">Read More</a>
                    </div>
                  </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}
    

templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock title %}

    {% block content %}
    {% include 'banner.html' %}
        <div class="container my-3">
            <div class="mb-4" style="text-align: center;">
                <h1 style="
                    display: inline-block;
                    padding: 5px;
                    background: linear-gradient(to right, #ff7e5f, #feb47b);
                    -webkit-background-clip: text;
                    color: transparent;
                    border-bottom: 3px solid #ff7e5f;
                ">Recent Events</h1>
            </div>
            <div class="row">
                
                {% for event in events %}
                    <div class="col-lg-6">
                        <div class="card shadow-sm mb-3">
                            <img src={{event.images.url}} class="card-img-top animated-image" alt="..." height="350">
                            <div class="card-body">
                              <h5 class="card-title">{{event.event_name}}</h5>
                              <p class="card-text">{{event.introduction|slice:":150"}}&nbsp;...</p>
                              <hr>
                              <a href="{% url 'main:event-details' event.slug %}" type="button" class="btn btn-outline-info align-items-center">Read More</a>
                            </div>
                          </div>
                    </div>
                {% endfor %}
                    
            </div>
            <div class="mt-4">
                <h1 class="text-center mb-5">{{about.title}}</h1>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <img src={{about.images.url}} alt="" style="width: 100%; max-width: 100%; border-radius: 15px;">
                </div>
                <div class="col-sm-6">
                    <p>{{about.text|linebreaks}}</p>
                </div>
            </div>
            <div class="mt-3 testimonial-slider">
                <h2 class="text-center mb-5">What Our Clients Say</h2>
                <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        {% for feedback in review %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <div class="d-flex justify-content-center align-items-center">
                                <div class="col-md-4">
                                    <div class="testimonial-card text-center">
                                        <img src={{feedback.image.url}} alt="" class="testimonial-img">
                                        <p>{{feedback.text}}</p>
                                        <p style="font-weight: bolder;">&#10077;{{ feedback.name }}&#10078;</p>
                                        <!-- Add other feedback attributes here -->
                                    </div>
                                </div>
                                <!-- Repeat this block for each testimonial attribute you want to display -->
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
            
            
            
        </div>
    {% endblock content %}
        

templates/main/media_library.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Media-Photos-Videos
{% endblock title %}


{% block content %}
<div class="d-flex flex-column justify-content-center align-items-center" style="height: 130px; background-color: #F4C431;">
    <h2 style="margin: 0; font-weight: bolder; letter-spacing: 2px;">Our Event Photos & Videos</h2>
</div>
<div class="container">
    <div class="mt-3 d-flex justify-content-center align-items-center">
        {% for event in event_name_list %}
            <a href="{% url 'main:photo-detail' event.id %}" type="button" class="btn btn-light shadow mx-2">{{event.event_name.event_name}}</a>
        {% endfor %}
    </div>
    <div class="mt-5">
        <div class="mb-4" style="text-align: center;">
            <h1 style="
                display: inline-block;
                padding: 5px;
                background: linear-gradient(to right, #ff7e5f, #feb47b);
                -webkit-background-clip: text;
                color: transparent;
                border-bottom: 3px solid #ff7e5f;
            ">Update Photos</h1>
        </div>
        <div class="row">  
            {% for img in event_img %}  
            <div class="col-sm-3">
                <img class="mb-3 shadow-sm" style="border-radius: 15px;" src={{img.photos.url}} alt="" width="100%" max-width="100%" height="300px">
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}
    
    

templates/main/photo_detail.html
{% extends 'base.html' %}


{% block title %}
    Photo Details
{% endblock title %}


{% block content %}
<div class="d-flex flex-column justify-content-center align-items-center" style="height: 130px; background-color: #F4C431;">
    <h2 style="margin: 0; font-weight: bolder; letter-spacing: 2px;">{{name}} update photos</h2>
</div>
<div class="container my-3">
    <div class="row">  
        {% for photo in photos %}  
        <div class="col-sm-3">
            <img class="mb-3 shadow-sm" style="border-radius: 15px;" src={{photo.photos.url}} alt="" width="100%" max-width="100%" height="300px">
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}
    

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
      <a class="navbar-brand" href="#">
          <!-- Your logo goes here -->
          <img style="border-radius: 15px;" src="{% static 'images/shiva.jpg' %}" alt="Logo" height="60" width="60">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
              <li class="nav-item mx-2">
                  <a class="nav-link" aria-current="page" href="{% url 'main:home' %}">Home</a>
              </li>
              <li class="nav-item mx-2">
                  <a class="nav-link" aria-current="page" href="{% url 'main:about' %}">About Us</a>
              </li>
              <li class="nav-item mx-2">
                  <a class="nav-link" aria-current="page" href="{% url 'main:event' %}">Events</a>
              </li>
              <li class="nav-item mx-2">
                  <a class="nav-link" aria-current="page" href="{% url 'main:media' %}">Media & Library</a>
              </li>
              <li class="nav-item mx-2">
                  <a class="nav-link" aria-current="page" href="{% url 'main:contact' %}">Contact Us</a>
              </li>
          </ul>
          <div class="d-flex mx-2">
              <a href="{% url 'main:donate' %}" class="btn btn-outline-success text-decoration-none" type="submit">Donation</a>
          </div>
      </div>
  </div>
</nav>